plugins {
    id 'java-library'
    id 'com.zeroc.gradle.ice-builder.slice' version '1.5.2'
}

repositories {
    mavenCentral()
}

slice {
    java {
        files = [file('src/main/slice/apexstore.ice')]
    }
}

dependencies {
    // Debe coincidir con la versión de slice2java (3.7.10)
    api 'com.zeroc:ice:3.7.10'
}